
project_id = "ycloufmcjjfvjxhmslbm"

[functions.sendProjectForm]
verify_jwt = true

[functions.receiveContentWebhook]
verify_jwt = false

[functions.linkedinAuth]
verify_jwt = false

[functions.linkedinAutomation]
verify_jwt = true

[functions.linkedinCompanyPost]
verify_jwt = true
